name: Repo Request
description: Solicitud de nuevo repositorio
title: 'Crear repositorio: '
labels: 
  - 'repo-request'
assignees: 
  - 'belcebus'
body:
  - type: input
    id: nombre_repositorio
    attributes:
      label: Nombre del repositorio
      description: Nombre del repositorio
      placeholder: nombre-del-repositorio
      value: nombre-repo-test
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: Descripci贸n del repositorio
      description: Descripci贸n del repositorio
      placeholder: Descripci贸n del repositorio
    validations:
      required: false
  - type: input
    id: team
    attributes:
      label: Admin team
      description: Equipo responsable de la administraci贸n del repositorio
      placeholder: equipo
    validations:
      required: false
#### nueva parte del formulario
  - type: dropdown
    id: options
    attributes:
      label: Source repository type
      description: Source repository type if needed, none by default
      multiple: false
      options:
        - 'template'
        - 'fork'
    validations:
      required: false
  - type: input
    id: repositorio_origen
    attributes:
      label: source repository / template
      description: The source repository / template to use in org/repo format
      placeholder: org/repo
    validations:
      required: false
