name: Repo Request
about: Solicitud de nuevo repositorio
title: 'Crear repositorio: '
labels: 'repo-request'
assignees: 'belcebus'
body:
  - type: input
    id: name
    attributes:
      label: Nombre del repositorio
      description: Nombre del repositorio
      placeholder: nombre-del-repositorio
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: Descripción del repositorio
      description: Descripción del repositorio
      placeholder: Descripción del repositorio
    validations:
      required: true
  - type: input
    id: team
    attributes:
      label: Equipo responsable
      description: Equipo responsable
      placeholder: equipo
