name: Repo Request
description: Solicitud de nuevo repositorio
title: 'Crear repositorio: '
labels: 
  - 'repo-request'
assignees: 
  - 'belcebus'
body:
  - type: input
    id: nombre_repositorio
    attributes:
      label: Nombre del repositorio
      description: Nombre del repositorio
      placeholder: nombre-del-repositorio
      value: nombre-repo-test
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: Descripci贸n del repositorio
      description: Descripci贸n del repositorio
      placeholder: Descripci贸n del repositorio
    validations:
      required: false
  - type: input
    id: team
    attributes:
      label: Admin team
      description: Equipo responsable de la administraci贸n del repositorio
      placeholder: equipo
    validations:
      required: false
#### nueva parte del formulario
  - type: options
    id: options
    attributes:
      label: origen del repositorio
      description: origen del repositorio
      options:
        -label: 'template'
          value: 'template'
        -label: 'fork'
          value: 'fork'
    validations:
      required: true
  - type: input
    id: repositorio_origen
    attributes:
      label: repositorio origen
      description: repositorio origen
      placeholder: org/repo
    validations:
      required: false
      