name: Create repo via issue form
on:
    issues:
        types: 
            - opened
            - edited

jobs:
    create-repo:
        name: Create repo via issue-form
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v3

            - name: Create repo
              uses: actions/github-script@v6
              with:
                github-token: ${{ secrets.MY_PAT }}
                script: | 
                  const script = require('${{github.workspace}}/main.js')
                  console.log(script({github, context, core}))
