name: Create repo via issue form
on:
    issues:
        types: 
            - opened
            - edited

jobs:
    read-form:
        name: read-form
        runs-on: ubuntu-latest
        steps:
            - name: read form
              run: |
                echo  ${{ github.event.issue.body }}
            - name: View context attributes
              uses: actions/github-script@v6
              with:
                script: console.log(context)
