name: Create repo via issue form

run-name: Execute create repo request from @${{ github.actor }}

on:
    issues:
        types: 
            - opened
            - edited

jobs:
    create-repo:
        name: Create repo via issue-form
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v3

            - name: Generate JWT
              id: generate_jwt
              uses: tibdex/github-app-jwt@v2
              with:
                app_id: ${{ secrets.APP_ID }}
                private_key: ${{ secrets.APP_PRIVATE_KEY }}
                installation_id: ${{ secrets.INSTALLATION_ID }}

            - name: Create repo
              id: create_repo
              uses: actions/github-script@v6
              with:
                github-token: ${{ steps.generate_jwt.outputs.token }}
                script: | 
                  const script = require('${{github.workspace}}/main.js')
                  await script({githApp, context, core})

              