name: Create repo via issue form
on:
    issues:
        types: 
            - opened
            - edited

jobs:
    read-form:
        name: read-form
        runs-on: ubuntu-latest
        steps:
            - name: View context attributes
              uses: actions/github-script@v6
              with:
                script: | 
                  //console.log(context)
                  let textoMultilinea = context.payload.issue.body
                  console.log(textoMultilinea)
                  let lineas = textoMultilinea.split("\n")
                  let terceraLinea = lineas[2]
                  console.log(terceraLinea); // Esto imprimirá "Esta es la tercera línea"
                  const regex = /^[a-z\d](?:[a-z\d]|-(?=[a-z\d])){0,38}/i;
                  if (regex.test(terceraLinea) && texto.startsWith("gln-")) {
                    console.log('La variable comienza con el prefijo y tiene un formato válido');
                  } else {
                    console.log('La variable no cumple con los requisitos');
                  }
                  
            - name: Acceder al campo personalizado nombre_repositorio
              id: extraer
              run: |
                echo "${{ github.event.issue.body }}" | sed -n '/Nombre del repositorio/{n;p;}' | sed -e 's/^[[:space:]]*//' | echo "::set-output name=nombre_repositorio::$(cat)"

            - name: Imprimir el nombre del repositorio
              run: |
                echo "El nombre del repositorio es ${{ steps.extraer.outputs.nombre_repositorio }}"
              
