name: Create repo via issue form
on:
    issues:
        types: 
            - opened
            - edited

jobs:
    read-form:
        name: read-form
        runs-on: ubuntu-latest
        steps:
            - name: read form
              run: |
                echo  "${{ github.event.issue.body }}"
            - name: View context attributes
              uses: actions/github-script@v6
              with:
                script: | 
                  console.log(context)

            - name: Acceder al campo personalizado nombre_repositorio
              id: extraer
              run: |
                run: echo "::set-output name=nombre_repositorio::$(echo ${GITHUB_EVENT_PATH} | xargs cat | grep -oP '(?<=Nombre del repositorio\n\n)[^\n]+')"

            - name: Imprimir el nombre del repositorio
              run: |
                echo "El nombre del repositorio es ${{ steps.extraer.outputs.nombre_repositorio }}"
              
