name: Create repo via issue form

run-name: Execute create repo request from @${{ github.actor }}

on:
    issues:
        types: 
            - opened
            - edited

jobs:
    create-repo:
        name: Create repo via issue-form
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                node-version: 16
                
            - name: Install dependencies
              run: npm install @octokit/rest @octokit/auth-app @actions/github

            - name: Generate JWT
              id: generate_jwt
              uses: actions/github-script@v6
              env: 
                APP_ID: ${{ secrets.APP_ID }}
                APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
                APP_INSTALLATION_ID: ${{ secrets.INSTALLATION_ID }}
              with:
                script: |
                  const { getOctokit } = require("@actions/github");
                  const { createAppAuth } = require("@octokit/auth-app");
                  const { request } = require("@octokit/request");

                  const app = createAppAuth({
                    appId: process.env.APP_ID,
                    privateKey: process.env.APP_PRIVATE_KEY,
                    request: request.defaults({
                      baseUrl: "${{ github.api_url }}"
                    }),
                  });

                  const authApp = await app({ type: "app" });
                  const octokit = await getOctokit( authApp.token );

                  try {
                    const { data: installation } =
                      await octokit.rest.apps.createInstallationAccessToken({
                        installation_id: process.env.APP_INSTALLATION_ID
                      });

                    const installationToken = installation.token;
                    core.setSecret(installationToken);
                    core.setOutput("token", installationToken);
                  } catch (error) {
                    core.setFailed(error.message);
                  }

            - name: Create repo
              uses: actions/github-script@v6
              with:
                github-token: ${{ steps.generate_jwt.outputs.token }}
                script: |
                  const script = require('${{github.workspace}}/.github/scripts/create-repo.js')
                  await script({github, context, core})

