name: Create repo via issue form

run-name: Execute create repo request from @${{ github.actor }}

on:
    issues:
        types: 
            - opened
            - edited

          
jobs:
    check-preconditions:
      name: Check preconditions
      runs-on: ubuntu-latest
      outputs:
        create-repo: ${{ steps.verify-label.outputs.result }}
      steps:
        - name: Verify issue type and label
          uses: actions/github-script@v6
          id: verify-label
          with:
            result-encoding: string
            script: |
                let result = false
                const labelContent = 'repo-request'
                context.payload.issue.labels.forEach(label => {
                    if (label.name === labelContent) {
                        core.info("Label: " + labelContent + " found")
                        result = true
                    }
                })
                return result
   
    get-auth-token:
        name: Create repo via issue-form
        if: needs.check-preconditions.outputs.create-repo == 'true'
        needs: check-preconditions
        runs-on: ubuntu-latest
        outputs:
          token: ${{ steps.set-output-token.outputs.TOKEN-B64 }}
        steps:

            - name: checkout repo
              uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                node-version: 16
                
            - name: Install dependencies
              run: npm install @octokit/rest @octokit/auth-app @actions/github

            - name: Generate JWT
              id: generate_jwt
              uses: actions/github-script@v6
              env: 
                APP_ID: ${{ secrets.APP_ID }}
                APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
                APP_INSTALLATION_ID: ${{ secrets.INSTALLATION_ID }}
              with:
                script: |
                  const { getOctokit } = require("@actions/github");
                  const { createAppAuth } = require("@octokit/auth-app");
                  const { request } = require("@octokit/request");

                  const app = createAppAuth({
                    appId: process.env.APP_ID,
                    privateKey: process.env.APP_PRIVATE_KEY,
                    request: request.defaults({
                      baseUrl: "${{ github.api_url }}"
                    }),
                  });

                  const authApp = await app({ type: "app" });
                  const octokit = await getOctokit( authApp.token );

                  try {
                    const { data: installation } =
                      await octokit.rest.apps.createInstallationAccessToken({
                        installation_id: process.env.APP_INSTALLATION_ID
                      });

                    const installationToken = installation.token;
                    core.setSecret(installationToken);
                    core.setOutput("token", installationToken);
                  } catch (error) {
                    core.setFailed(error.message);
                  }
            - name: set output-token
              id: set-output-token
              run: |
                AUX=$(echo ${{ steps.generate_jwt.outputs.token }} | base64)
                TOKEN-B64=$(echo $AUX) >> $GITHUB_OUTPUT

    create-repo:
        runs-on: ubuntu-latest
        needs: get-auth-token
        steps:
          - name: decode token
            id: decode-token
            run: |
                AUX=$(echo ${{ needs.get-auth-token.outputs.TOKEN-B64 }} | base64 --decode)
                TOKEN=$(echo AUX) >> $GITHUB_OUTPUT
          - name: Create repo
            uses: actions/github-script@v6
            with:
                github-token: ${{ steps.decode-token.outputs.TOKEN }}
                script: |
                    const script = require('${{github.workspace}}/.github/scripts/create-repo.js')
                    await script({github, context, core})

