name: Execute request

run-name: Execute request from @${{ github.actor }}

on:
    issues:
        types: 
            - opened
            - edited
          
jobs:
    check-preconditions:
      name: Check preconditions
      runs-on: ubuntu-latest
      outputs:
        preconditions-ok: ${{ steps.verify-label.outputs.result }}
        job-type: ${{ steps.verify-label.outputs.job-type }}

      steps:
        - name: Verify issue type and label
          uses: actions/github-script@v6
          id: verify-label
          with:
            result-encoding: string
            script: |
                let result = false
                context.payload.issue.labels.forEach(label => {
                    if (label.name === "repo-request") {
                        core.info("Label: " + "repo-request" + " found")
                        core.setOutput("job-type", "repo-request");
                        result = true
                    }else if (label.name === "action-validation-request") {
                        core.info("Label: " + "action-validation-request" + " found")
                        core.setOutput("job-type", "action-validation-request");
                        result = true
                    }
                })
                return result
   
    get-auth-token:
        name: Generate auth token
        if: needs.check-preconditions.outputs.preconditions-ok == 'true'
        needs: check-preconditions
        runs-on: ubuntu-latest
        outputs:
          TOKENB64: ${{ steps.set-output-token.outputs.TOKENB64 }}
        steps:

            - name: checkout repo
              uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                node-version: 16
                
            - name: Install dependencies
              run: npm install @octokit/rest @octokit/auth-app @actions/github

            - name: Generate JWT
              id: generate_jwt
              uses: actions/github-script@v6
              env: 
                APP_ID: ${{ secrets.APP_ID }}
                APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
                APP_INSTALLATION_ID: ${{ secrets.INSTALLATION_ID }}
              with:
                script: |
                  const { getOctokit } = require("@actions/github");
                  const { createAppAuth } = require("@octokit/auth-app");
                  const { request } = require("@octokit/request");

                  const app = createAppAuth({
                    appId: process.env.APP_ID,
                    privateKey: process.env.APP_PRIVATE_KEY,
                    request: request.defaults({
                      baseUrl: "${{ github.api_url }}"
                    }),
                  });

                  const authApp = await app({ type: "app" });
                  const octokit = await getOctokit( authApp.token );

                  try {
                    const { data: installation } =
                      await octokit.rest.apps.createInstallationAccessToken({
                        installation_id: process.env.APP_INSTALLATION_ID
                      });

                    const installationToken = installation.token;
                    core.setSecret(installationToken);
                    core.setOutput("token", installationToken);
                  } catch (error) {
                    core.setFailed(error.message);
                  }
            - name: set output-token
              id: set-output-token
              run: |
                AUX=$(echo ${{ steps.generate_jwt.outputs.token }} | base64)
                echo "TOKENB64=$AUX" >> $GITHUB_OUTPUT

    create-repo:
        name: Create repo
        if: needs.check-preconditions.outputs.job-type == 'repo-request'
        runs-on: ubuntu-latest
        needs: get-auth-token
        steps:

          - name: checkout repo
            uses: actions/checkout@v3          

          - name: decode token
            id: decode-token
            run: |
                AUX=$(echo ${{ needs.get-auth-token.outputs.TOKENB64 }} | base64 --decode)
                echo "TOKEN=$AUX" >> $GITHUB_OUTPUT
          - name: Create repo
            uses: actions/github-script@v6
            with:
                github-token: ${{ steps.decode-token.outputs.TOKEN }}
                script: |
                    const script = require('${{github.workspace}}/.github/scripts/preconditions-ok.js')
                    await script({github, context, core})

    validate-action:
        name: Validate action
        if: needs.check-preconditions.outputs.job-type == 'action-validation-request'
        runs-on: ubuntu-latest
        needs: get-auth-token
        steps:
    
          - name: checkout repo
            uses: actions/checkout@v3          

          - name: decode token
            id: decode-token
            run: |
                AUX=$(echo ${{ needs.get-auth-token.outputs.TOKENB64 }} | base64 --decode)
                echo "TOKEN=$AUX" >> $GITHUB_OUTPUT
