name: Create repo via issue form
on:
    issues:
        types: 
            - opened
            - edited

jobs:
    read-form:
        name: read-form
        runs-on: ubuntu-latest
        steps:
            - name: View context attributes
              uses: actions/github-script@v6
              env:
                GLUON_PREFIX: "gln-"
              with:
                script: | 
                  console.log(context.payload.issue.body);
                  console.log("******************");
                  let noResponse = "_No response_";

                  let lineas = context.payload.issue.body.split("\n");
                  let repoName = lineas[2];
                  let repoDescription = lineas[6]
                  let adminTeam = lineas[10]
                  
                  if (repoDescription == noResponse){
                    repoDescription = "";
                  }
                  if (adminTeam == noResponse){
                    adminTeam = ""
                  }

                  core.debug("Repository name: " + repoName)
                  core.debug("Repository description: " + repoDescription)
                  core.debug("Admin team: " + adminTeam)
                  
                  const regex = /^[a-z\d](?:[a-z\d]|-(?=[a-z\d])){0,38}/i;
                  if (regex.test(repoName) && repoName.startsWith("${GLUON_PREFIX}")) {
                    core.info('El nombre del repositorio solicitado comienza con el prefijo y tiene un formato válido');

                  } else {
                    core.setFailed(`El nombre del repositorio ${repoName} no cumple con los requisitos`);
                  }
                  
            - name: Acceder al campo personalizado nombre_repositorio
              id: extraer
              run: |
                echo "${{ github.event.issue.body }}" | sed -n '/Nombre del repositorio/{n;p;}' | sed -e 's/^[[:space:]]*//' | echo "::set-output name=nombre_repositorio::$(cat)"

            - name: Imprimir el nombre del repositorio
              run: |
                echo "El nombre del repositorio es ${{ steps.extraer.outputs.nombre_repositorio }}"
              
