name: get jwt token test

run-name: Get jwt token test

on:
  workflow_dispatch:

jobs:
    create-repo:
        name: Create repo via issue-form
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                node-version: 16
                
            - name: Install dependencies
              run: npm install @octokit/rest @octokit/auth-app

            - name: Generate JWT
              id: generate_jwt
              uses: actions/github-script@v6
              env: 
                APP_ID: ${{ secrets.APP_ID }}
                APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
                APP_INSTALLATION_ID: ${{ secrets.INSTALLATION_ID }}
              with:
                script: |
                  const { Octokit } = require("@octokit/rest");
                  const { createAppAuth } = require("@octokit/auth-app");
                  const appOctokit = new Octokit({
                    authStrategy: createAppAuth,
                    auth: {
                      appId: process.env.APP_ID,
                      privateKey: process.env.APP_PRIVATE_KEY,
                      installationId: process.env.APP_INSTALLATION_ID,
                    },
                  });

                  const { token } = await appOctokit.auth({
                    type: "installation",
                  });

                  return token;

            - name: Show token
              run: echo ${{ steps.generate_jwt.outputs.token }}
              